version: '3.3'

services:
  jenkins:
    container_name: jenkins
    image: frelaxy/jenkins:latest
    volumes:
     - ./data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
